package myapp.appconfig;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;
public class SecurityWebApplicationInit extends AbstractSecurityWebApplicationInitializer {
}